PRAGMA foreign_keys = ON;

CREATE TABLE sources (
    sort_order INTEGER NOT NULL UNIQUE CHECK (sort_order >= 0),
    source_id TEXT PRIMARY KEY,
    source_type TEXT NOT NULL CHECK (source_type IN ('aggregator', 'company_career')),
    transport TEXT NOT NULL CHECK (transport IN ('http', 'browser', 'hybrid')),
    source_limit INTEGER NOT NULL CHECK (source_limit > 0)
);

CREATE TABLE countries (
    country_code TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    search_enabled INTEGER NOT NULL CHECK (search_enabled IN (0, 1))
);

CREATE TABLE source_countries (
    source_id TEXT NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    country_order INTEGER NOT NULL CHECK (country_order >= 0),
    country TEXT NOT NULL REFERENCES countries(country_code),
    PRIMARY KEY (source_id, country),
    UNIQUE (source_id, country_order)
);

CREATE TABLE source_criteria (
    source_id TEXT NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    criterion_order INTEGER NOT NULL CHECK (criterion_order >= 0),
    criterion TEXT NOT NULL CHECK (
        criterion IN (
            'query',
            'grades',
            'salary_from',
            'published_since',
            'relocation',
            'remote_mode',
            'work_from_geographies',
            'vacancy_geographies',
            'cities'
        )
    ),
    capability TEXT NOT NULL CHECK (
        capability IN ('native_request', 'structured_output', 'unsupported')
    ),
    PRIMARY KEY (source_id, criterion),
    UNIQUE (source_id, criterion_order)
);

CREATE TABLE source_required_fixture_kinds (
    source_id TEXT NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (
        kind IN (
            'no_results',
            'pagination',
            'detail',
            'optional_fields',
            'blocked',
            'rate_limited',
            'login',
            'geo_blocked',
            'malformed_source'
        )
    ),
    PRIMARY KEY (source_id, kind)
);

CREATE TABLE parser_fixtures (
    source_id TEXT NOT NULL REFERENCES sources(source_id) ON DELETE CASCADE,
    fixture_order INTEGER NOT NULL CHECK (fixture_order >= 0),
    name TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (
        kind IN (
            'success_non_empty',
            'no_results',
            'pagination',
            'detail',
            'optional_fields',
            'blocked',
            'rate_limited',
            'login',
            'geo_blocked',
            'malformed_source'
        )
    ),
    captured_artifact_path TEXT NOT NULL,
    metadata_path TEXT NOT NULL,
    golden_path TEXT NOT NULL,
    real_capture INTEGER NOT NULL CHECK (real_capture IN (0, 1)),
    golden_reviewed_by TEXT NOT NULL,
    PRIMARY KEY (source_id, name),
    UNIQUE (source_id, fixture_order)
);

INSERT INTO sources (sort_order, source_id, source_type, transport, source_limit)
VALUES
    (0, 'habr_career', 'aggregator', 'http', 50),
    (1, 'hh_ru', 'aggregator', 'http', 100),
    (2, 'talanto', 'aggregator', 'http', 50),
    (3, 'career:vk', 'company_career', 'http', 300),
    (4, 'career:jetbrains', 'company_career', 'http', 120),
    (5, 'geekjob', 'aggregator', 'http', 50),
    (6, 'talento', 'aggregator', 'http', 50),
    (7, 'finder_work', 'aggregator', 'http', 100),
    (8, 'getmatch', 'aggregator', 'http', 100),
    (9, 'it_jobs_uz', 'aggregator', 'http', 100),
    (10, 'hirify', 'aggregator', 'http', 100),
    (11, 'jobturbo', 'aggregator', 'http', 50),
    (12, 'hirehi', 'aggregator', 'http', 50),
    (13, 'staff_am', 'aggregator', 'http', 100),
    (14, 'career:ibs', 'company_career', 'http', 100),
    (15, 'career:amocrm', 'company_career', 'http', 50),
    (16, 'career:coinspaid', 'company_career', 'http', 100),
    (17, 'career:appfollow', 'company_career', 'http', 20),
    (18, 'career:airslate', 'company_career', 'http', 100);

INSERT INTO countries (country_code, display_name, search_enabled)
VALUES
    ('RU', 'Russia', 1),
    ('AM', 'Armenia', 1);

INSERT INTO source_countries (source_id, country_order, country)
VALUES
    ('habr_career', 0, 'RU'),
    ('hh_ru', 0, 'RU'),
    ('career:vk', 0, 'RU'),
    ('career:ibs', 0, 'RU'),
    ('career:amocrm', 0, 'RU'),
    ('hirehi', 0, 'RU'),
    ('staff_am', 0, 'AM');

INSERT INTO source_criteria (source_id, criterion_order, criterion, capability)
VALUES
    ('habr_career', 0, 'query', 'native_request'),
    ('habr_career', 1, 'grades', 'native_request'),
    ('habr_career', 2, 'salary_from', 'native_request'),
    ('habr_career', 3, 'published_since', 'structured_output'),
    ('habr_career', 4, 'relocation', 'unsupported'),
    ('habr_career', 5, 'remote_mode', 'structured_output'),
    ('habr_career', 6, 'work_from_geographies', 'structured_output'),
    ('habr_career', 7, 'vacancy_geographies', 'structured_output'),
    ('habr_career', 8, 'cities', 'structured_output'),
    ('hh_ru', 0, 'query', 'native_request'),
    ('hh_ru', 1, 'grades', 'structured_output'),
    ('hh_ru', 2, 'salary_from', 'native_request'),
    ('hh_ru', 3, 'published_since', 'structured_output'),
    ('hh_ru', 4, 'relocation', 'unsupported'),
    ('hh_ru', 5, 'remote_mode', 'structured_output'),
    ('hh_ru', 6, 'work_from_geographies', 'structured_output'),
    ('hh_ru', 7, 'vacancy_geographies', 'structured_output'),
    ('hh_ru', 8, 'cities', 'structured_output'),
    ('talanto', 0, 'query', 'native_request'),
    ('talanto', 1, 'grades', 'structured_output'),
    ('talanto', 2, 'salary_from', 'structured_output'),
    ('talanto', 3, 'published_since', 'structured_output'),
    ('talanto', 4, 'relocation', 'unsupported'),
    ('talanto', 5, 'remote_mode', 'structured_output'),
    ('talanto', 6, 'work_from_geographies', 'structured_output'),
    ('talanto', 7, 'vacancy_geographies', 'structured_output'),
    ('talanto', 8, 'cities', 'structured_output'),
    ('career:vk', 0, 'query', 'structured_output'),
    ('career:vk', 1, 'grades', 'unsupported'),
    ('career:vk', 2, 'salary_from', 'unsupported'),
    ('career:vk', 3, 'published_since', 'unsupported'),
    ('career:vk', 4, 'relocation', 'unsupported'),
    ('career:vk', 5, 'remote_mode', 'structured_output'),
    ('career:vk', 6, 'work_from_geographies', 'structured_output'),
    ('career:vk', 7, 'vacancy_geographies', 'structured_output'),
    ('career:vk', 8, 'cities', 'structured_output'),
    ('career:jetbrains', 0, 'query', 'structured_output'),
    ('career:jetbrains', 1, 'grades', 'unsupported'),
    ('career:jetbrains', 2, 'salary_from', 'unsupported'),
    ('career:jetbrains', 3, 'published_since', 'structured_output'),
    ('career:jetbrains', 4, 'relocation', 'unsupported'),
    ('career:jetbrains', 5, 'remote_mode', 'structured_output'),
    ('career:jetbrains', 6, 'work_from_geographies', 'structured_output'),
    ('career:jetbrains', 7, 'vacancy_geographies', 'structured_output'),
    ('career:jetbrains', 8, 'cities', 'structured_output'),
    ('career:ibs', 0, 'query', 'structured_output'),
    ('career:ibs', 1, 'grades', 'unsupported'),
    ('career:ibs', 2, 'salary_from', 'unsupported'),
    ('career:ibs', 3, 'published_since', 'unsupported'),
    ('career:ibs', 4, 'relocation', 'unsupported'),
    ('career:ibs', 5, 'remote_mode', 'structured_output'),
    ('career:ibs', 6, 'work_from_geographies', 'structured_output'),
    ('career:ibs', 7, 'vacancy_geographies', 'structured_output'),
    ('career:ibs', 8, 'cities', 'unsupported'),
    ('geekjob', 0, 'query', 'structured_output'),
    ('geekjob', 1, 'grades', 'unsupported'),
    ('geekjob', 2, 'salary_from', 'structured_output'),
    ('geekjob', 3, 'published_since', 'structured_output'),
    ('geekjob', 4, 'relocation', 'unsupported'),
    ('geekjob', 5, 'remote_mode', 'structured_output'),
    ('geekjob', 6, 'work_from_geographies', 'structured_output'),
    ('geekjob', 7, 'vacancy_geographies', 'structured_output'),
    ('geekjob', 8, 'cities', 'unsupported'),
    ('talento', 0, 'query', 'native_request'),
    ('talento', 1, 'grades', 'unsupported'),
    ('talento', 2, 'salary_from', 'unsupported'),
    ('talento', 3, 'published_since', 'unsupported'),
    ('talento', 4, 'relocation', 'unsupported'),
    ('talento', 5, 'remote_mode', 'unsupported'),
    ('talento', 6, 'work_from_geographies', 'unsupported'),
    ('talento', 7, 'vacancy_geographies', 'unsupported'),
    ('talento', 8, 'cities', 'unsupported'),
    ('finder_work', 0, 'query', 'native_request'),
    ('finder_work', 1, 'grades', 'structured_output'),
    ('finder_work', 2, 'salary_from', 'native_request'),
    ('finder_work', 3, 'published_since', 'structured_output'),
    ('finder_work', 4, 'relocation', 'unsupported'),
    ('finder_work', 5, 'remote_mode', 'structured_output'),
    ('finder_work', 6, 'work_from_geographies', 'structured_output'),
    ('finder_work', 7, 'vacancy_geographies', 'structured_output'),
    ('finder_work', 8, 'cities', 'structured_output'),
    ('getmatch', 0, 'query', 'native_request'),
    ('getmatch', 1, 'grades', 'unsupported'),
    ('getmatch', 2, 'salary_from', 'unsupported'),
    ('getmatch', 3, 'published_since', 'structured_output'),
    ('getmatch', 4, 'relocation', 'unsupported'),
    ('getmatch', 5, 'remote_mode', 'structured_output'),
    ('getmatch', 6, 'work_from_geographies', 'structured_output'),
    ('getmatch', 7, 'vacancy_geographies', 'structured_output'),
    ('getmatch', 8, 'cities', 'structured_output'),
    ('it_jobs_uz', 0, 'query', 'native_request'),
    ('it_jobs_uz', 1, 'grades', 'structured_output'),
    ('it_jobs_uz', 2, 'salary_from', 'native_request'),
    ('it_jobs_uz', 3, 'published_since', 'structured_output'),
    ('it_jobs_uz', 4, 'relocation', 'unsupported'),
    ('it_jobs_uz', 5, 'remote_mode', 'structured_output'),
    ('it_jobs_uz', 6, 'work_from_geographies', 'structured_output'),
    ('it_jobs_uz', 7, 'vacancy_geographies', 'structured_output'),
    ('it_jobs_uz', 8, 'cities', 'structured_output'),
    ('hirify', 0, 'query', 'native_request'),
    ('hirify', 1, 'grades', 'structured_output'),
    ('hirify', 2, 'salary_from', 'native_request'),
    ('hirify', 3, 'published_since', 'structured_output'),
    ('hirify', 4, 'relocation', 'unsupported'),
    ('hirify', 5, 'remote_mode', 'structured_output'),
    ('hirify', 6, 'work_from_geographies', 'structured_output'),
    ('hirify', 7, 'vacancy_geographies', 'structured_output'),
    ('hirify', 8, 'cities', 'structured_output'),
    ('jobturbo', 0, 'query', 'structured_output'),
    ('jobturbo', 1, 'grades', 'structured_output'),
    ('jobturbo', 2, 'salary_from', 'structured_output'),
    ('jobturbo', 3, 'published_since', 'unsupported'),
    ('jobturbo', 4, 'relocation', 'unsupported'),
    ('jobturbo', 5, 'remote_mode', 'structured_output'),
    ('jobturbo', 6, 'work_from_geographies', 'structured_output'),
    ('jobturbo', 7, 'vacancy_geographies', 'unsupported'),
    ('jobturbo', 8, 'cities', 'unsupported'),
    ('hirehi', 0, 'query', 'native_request'),
    ('hirehi', 1, 'grades', 'structured_output'),
    ('hirehi', 2, 'salary_from', 'structured_output'),
    ('hirehi', 3, 'published_since', 'unsupported'),
    ('hirehi', 4, 'relocation', 'unsupported'),
    ('hirehi', 5, 'remote_mode', 'structured_output'),
    ('hirehi', 6, 'work_from_geographies', 'structured_output'),
    ('hirehi', 7, 'vacancy_geographies', 'structured_output'),
    ('hirehi', 8, 'cities', 'structured_output'),
    ('staff_am', 0, 'query', 'native_request'),
    ('staff_am', 1, 'grades', 'structured_output'),
    ('staff_am', 2, 'salary_from', 'unsupported'),
    ('staff_am', 3, 'published_since', 'structured_output'),
    ('staff_am', 4, 'relocation', 'structured_output'),
    ('staff_am', 5, 'remote_mode', 'structured_output'),
    ('staff_am', 6, 'work_from_geographies', 'structured_output'),
    ('staff_am', 7, 'vacancy_geographies', 'structured_output'),
    ('staff_am', 8, 'cities', 'structured_output'),
    ('career:amocrm', 0, 'query', 'structured_output'),
    ('career:amocrm', 1, 'grades', 'unsupported'),
    ('career:amocrm', 2, 'salary_from', 'unsupported'),
    ('career:amocrm', 3, 'published_since', 'unsupported'),
    ('career:amocrm', 4, 'relocation', 'unsupported'),
    ('career:amocrm', 5, 'remote_mode', 'unsupported'),
    ('career:amocrm', 6, 'work_from_geographies', 'unsupported'),
    ('career:amocrm', 7, 'vacancy_geographies', 'structured_output'),
    ('career:amocrm', 8, 'cities', 'unsupported'),
    ('career:coinspaid', 0, 'query', 'structured_output'),
    ('career:coinspaid', 1, 'grades', 'unsupported'),
    ('career:coinspaid', 2, 'salary_from', 'unsupported'),
    ('career:coinspaid', 3, 'published_since', 'structured_output'),
    ('career:coinspaid', 4, 'relocation', 'unsupported'),
    ('career:coinspaid', 5, 'remote_mode', 'structured_output'),
    ('career:coinspaid', 6, 'work_from_geographies', 'structured_output'),
    ('career:coinspaid', 7, 'vacancy_geographies', 'structured_output'),
    ('career:coinspaid', 8, 'cities', 'structured_output'),
    ('career:appfollow', 0, 'query', 'structured_output'),
    ('career:appfollow', 1, 'grades', 'unsupported'),
    ('career:appfollow', 2, 'salary_from', 'unsupported'),
    ('career:appfollow', 3, 'published_since', 'structured_output'),
    ('career:appfollow', 4, 'relocation', 'unsupported'),
    ('career:appfollow', 5, 'remote_mode', 'structured_output'),
    ('career:appfollow', 6, 'work_from_geographies', 'structured_output'),
    ('career:appfollow', 7, 'vacancy_geographies', 'structured_output'),
    ('career:appfollow', 8, 'cities', 'unsupported'),
    ('career:airslate', 0, 'query', 'structured_output'),
    ('career:airslate', 1, 'grades', 'unsupported'),
    ('career:airslate', 2, 'salary_from', 'unsupported'),
    ('career:airslate', 3, 'published_since', 'structured_output'),
    ('career:airslate', 4, 'relocation', 'unsupported'),
    ('career:airslate', 5, 'remote_mode', 'structured_output'),
    ('career:airslate', 6, 'work_from_geographies', 'structured_output'),
    ('career:airslate', 7, 'vacancy_geographies', 'structured_output'),
    ('career:airslate', 8, 'cities', 'unsupported');

INSERT INTO source_required_fixture_kinds (source_id, kind)
VALUES
    ('habr_career', 'no_results'),
    ('habr_career', 'pagination'),
    ('habr_career', 'detail'),
    ('habr_career', 'optional_fields'),
    ('hh_ru', 'no_results'),
    ('hh_ru', 'pagination'),
    ('hh_ru', 'detail'),
    ('hh_ru', 'optional_fields'),
    ('hh_ru', 'blocked'),
    ('talanto', 'no_results'),
    ('talanto', 'detail'),
    ('career:vk', 'pagination'),
    ('career:vk', 'detail'),
    ('geekjob', 'no_results'),
    ('geekjob', 'detail'),
    ('talento', 'no_results'),
    ('talento', 'detail'),
    ('finder_work', 'no_results'),
    ('finder_work', 'detail'),
    ('getmatch', 'no_results'),
    ('it_jobs_uz', 'no_results'),
    ('hirify', 'no_results'),
    ('hirify', 'detail'),
    ('jobturbo', 'no_results'),
    ('hirehi', 'no_results'),
    ('hirehi', 'detail'),
    ('staff_am', 'no_results'),
    ('staff_am', 'detail'),
    ('career:ibs', 'pagination'),
    ('career:ibs', 'detail'),
    ('career:amocrm', 'detail'),
    ('career:appfollow', 'detail');

INSERT INTO parser_fixtures (
    source_id,
    fixture_order,
    name,
    kind,
    captured_artifact_path,
    metadata_path,
    golden_path,
    real_capture,
    golden_reviewed_by
)
VALUES
    (
        'habr_career',
        0,
        'habr_career-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/habr_career/success/response.html',
        'tests/v2/fixtures/scrapers/habr_career/success/meta.json',
        'tests/v2/fixtures/scrapers/habr_career/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'habr_career',
        1,
        'habr_career-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/habr_career/no_results/response.html',
        'tests/v2/fixtures/scrapers/habr_career/no_results/meta.json',
        'tests/v2/fixtures/scrapers/habr_career/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'habr_career',
        2,
        'habr_career-pagination',
        'pagination',
        'tests/v2/fixtures/scrapers/habr_career/pagination/response.html',
        'tests/v2/fixtures/scrapers/habr_career/pagination/meta.json',
        'tests/v2/fixtures/scrapers/habr_career/pagination/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'habr_career',
        3,
        'habr_career-detail',
        'detail',
        'tests/v2/fixtures/scrapers/habr_career/detail/response.html',
        'tests/v2/fixtures/scrapers/habr_career/detail/meta.json',
        'tests/v2/fixtures/scrapers/habr_career/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'habr_career',
        4,
        'habr_career-optional_fields',
        'optional_fields',
        'tests/v2/fixtures/scrapers/habr_career/success/response.html',
        'tests/v2/fixtures/scrapers/habr_career/optional_fields/meta.json',
        'tests/v2/fixtures/scrapers/habr_career/optional_fields/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hh_ru',
        0,
        'hh_ru-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/hh_ru/success/response.html',
        'tests/v2/fixtures/scrapers/hh_ru/success/meta.json',
        'tests/v2/fixtures/scrapers/hh_ru/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hh_ru',
        1,
        'hh_ru-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/hh_ru/no_results/response.html',
        'tests/v2/fixtures/scrapers/hh_ru/no_results/meta.json',
        'tests/v2/fixtures/scrapers/hh_ru/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hh_ru',
        2,
        'hh_ru-pagination',
        'pagination',
        'tests/v2/fixtures/scrapers/hh_ru/pagination/response.html',
        'tests/v2/fixtures/scrapers/hh_ru/pagination/meta.json',
        'tests/v2/fixtures/scrapers/hh_ru/pagination/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hh_ru',
        3,
        'hh_ru-detail',
        'detail',
        'tests/v2/fixtures/scrapers/hh_ru/detail/response.html',
        'tests/v2/fixtures/scrapers/hh_ru/detail/meta.json',
        'tests/v2/fixtures/scrapers/hh_ru/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hh_ru',
        4,
        'hh_ru-blocked',
        'blocked',
        'tests/v2/fixtures/scrapers/hh_ru/blocked/response.html',
        'tests/v2/fixtures/scrapers/hh_ru/blocked/meta.json',
        'tests/v2/fixtures/scrapers/hh_ru/blocked/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hh_ru',
        5,
        'hh_ru-optional_fields',
        'optional_fields',
        'tests/v2/fixtures/scrapers/hh_ru/success/response.html',
        'tests/v2/fixtures/scrapers/hh_ru/optional_fields/meta.json',
        'tests/v2/fixtures/scrapers/hh_ru/optional_fields/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        0,
        'career:vk-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/career_vk/success/response.json',
        'tests/v2/fixtures/scrapers/career_vk/success/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        1,
        'career:vk-pagination',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        2,
        'career:vk-pagination-offset-50',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_50/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_50/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_50/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        3,
        'career:vk-pagination-offset-75',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_75/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_75/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_75/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        4,
        'career:vk-pagination-offset-100',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_100/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_100/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_100/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        5,
        'career:vk-pagination-offset-125',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_125/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_125/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_125/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        6,
        'career:vk-pagination-offset-150',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_150/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_150/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_150/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        7,
        'career:vk-pagination-offset-175',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_175/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_175/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_175/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        8,
        'career:vk-pagination-offset-200',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_200/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_200/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_200/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        9,
        'career:vk-pagination-offset-225',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_225/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_225/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_225/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        10,
        'career:vk-pagination-offset-250',
        'pagination',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_250/response.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_250/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/pagination_offset_250/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'talanto',
        0,
        'talanto-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/talanto/success/response.html',
        'tests/v2/fixtures/scrapers/talanto/success/meta.json',
        'tests/v2/fixtures/scrapers/talanto/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'talanto',
        1,
        'talanto-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/talanto/no_results/response.html',
        'tests/v2/fixtures/scrapers/talanto/no_results/meta.json',
        'tests/v2/fixtures/scrapers/talanto/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'talanto',
        2,
        'talanto-detail',
        'detail',
        'tests/v2/fixtures/scrapers/talanto/detail/response.html',
        'tests/v2/fixtures/scrapers/talanto/detail/meta.json',
        'tests/v2/fixtures/scrapers/talanto/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:jetbrains',
        0,
        'career:jetbrains-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/career_jetbrains/success/response.json',
        'tests/v2/fixtures/scrapers/career_jetbrains/success/meta.json',
        'tests/v2/fixtures/scrapers/career_jetbrains/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'geekjob',
        0,
        'geekjob-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/geekjob/success/response.html',
        'tests/v2/fixtures/scrapers/geekjob/success/meta.json',
        'tests/v2/fixtures/scrapers/geekjob/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'geekjob',
        1,
        'geekjob-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/geekjob/no_results/response.html',
        'tests/v2/fixtures/scrapers/geekjob/no_results/meta.json',
        'tests/v2/fixtures/scrapers/geekjob/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'geekjob',
        2,
        'geekjob-detail',
        'detail',
        'tests/v2/fixtures/scrapers/geekjob/detail/response.html',
        'tests/v2/fixtures/scrapers/geekjob/detail/meta.json',
        'tests/v2/fixtures/scrapers/geekjob/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'talento',
        0,
        'talento-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/talento/success/response.html',
        'tests/v2/fixtures/scrapers/talento/success/meta.json',
        'tests/v2/fixtures/scrapers/talento/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'talento',
        1,
        'talento-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/talento/no_results/response.html',
        'tests/v2/fixtures/scrapers/talento/no_results/meta.json',
        'tests/v2/fixtures/scrapers/talento/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'finder_work',
        0,
        'finder_work-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/finder_work/success/response.json',
        'tests/v2/fixtures/scrapers/finder_work/success/meta.json',
        'tests/v2/fixtures/scrapers/finder_work/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'finder_work',
        1,
        'finder_work-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/finder_work/no_results/response.json',
        'tests/v2/fixtures/scrapers/finder_work/no_results/meta.json',
        'tests/v2/fixtures/scrapers/finder_work/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'getmatch',
        0,
        'getmatch-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/getmatch/success/response.json',
        'tests/v2/fixtures/scrapers/getmatch/success/meta.json',
        'tests/v2/fixtures/scrapers/getmatch/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'getmatch',
        1,
        'getmatch-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/getmatch/no_results/response.json',
        'tests/v2/fixtures/scrapers/getmatch/no_results/meta.json',
        'tests/v2/fixtures/scrapers/getmatch/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'it_jobs_uz',
        0,
        'it_jobs_uz-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/it_jobs_uz/success/response.json',
        'tests/v2/fixtures/scrapers/it_jobs_uz/success/meta.json',
        'tests/v2/fixtures/scrapers/it_jobs_uz/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'it_jobs_uz',
        1,
        'it_jobs_uz-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/it_jobs_uz/no_results/response.json',
        'tests/v2/fixtures/scrapers/it_jobs_uz/no_results/meta.json',
        'tests/v2/fixtures/scrapers/it_jobs_uz/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hirify',
        0,
        'hirify-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/hirify/success/response.json',
        'tests/v2/fixtures/scrapers/hirify/success/meta.json',
        'tests/v2/fixtures/scrapers/hirify/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hirify',
        1,
        'hirify-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/hirify/no_results/response.json',
        'tests/v2/fixtures/scrapers/hirify/no_results/meta.json',
        'tests/v2/fixtures/scrapers/hirify/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hirify',
        2,
        'hirify-detail',
        'detail',
        'tests/v2/fixtures/scrapers/hirify/detail/response.json',
        'tests/v2/fixtures/scrapers/hirify/detail/meta.json',
        'tests/v2/fixtures/scrapers/hirify/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'jobturbo',
        0,
        'jobturbo-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/jobturbo/success/response.html',
        'tests/v2/fixtures/scrapers/jobturbo/success/meta.json',
        'tests/v2/fixtures/scrapers/jobturbo/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'jobturbo',
        1,
        'jobturbo-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/jobturbo/no_results/response.html',
        'tests/v2/fixtures/scrapers/jobturbo/no_results/meta.json',
        'tests/v2/fixtures/scrapers/jobturbo/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hirehi',
        0,
        'hirehi-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/hirehi/success/response.html',
        'tests/v2/fixtures/scrapers/hirehi/success/meta.json',
        'tests/v2/fixtures/scrapers/hirehi/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hirehi',
        1,
        'hirehi-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/hirehi/no_results/response.html',
        'tests/v2/fixtures/scrapers/hirehi/no_results/meta.json',
        'tests/v2/fixtures/scrapers/hirehi/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'staff_am',
        0,
        'staff_am-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/staff_am/success/response.html',
        'tests/v2/fixtures/scrapers/staff_am/success/meta.json',
        'tests/v2/fixtures/scrapers/staff_am/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'staff_am',
        1,
        'staff_am-no_results',
        'no_results',
        'tests/v2/fixtures/scrapers/staff_am/no_results/response.html',
        'tests/v2/fixtures/scrapers/staff_am/no_results/meta.json',
        'tests/v2/fixtures/scrapers/staff_am/no_results/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'habr_career',
        5,
        'habr_career-detail-sectioned',
        'detail',
        'tests/v2/fixtures/scrapers/habr_career/detail_sectioned/response.html',
        'tests/v2/fixtures/scrapers/habr_career/detail_sectioned/meta.json',
        'tests/v2/fixtures/scrapers/habr_career/detail_sectioned/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:vk',
        11,
        'career:vk-detail',
        'detail',
        'tests/v2/fixtures/scrapers/career_vk/detail/response.html',
        'tests/v2/fixtures/scrapers/career_vk/detail/meta.json',
        'tests/v2/fixtures/scrapers/career_vk/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'talento',
        2,
        'talento-detail',
        'detail',
        'tests/v2/fixtures/scrapers/talento/detail/response.html',
        'tests/v2/fixtures/scrapers/talento/detail/meta.json',
        'tests/v2/fixtures/scrapers/talento/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'finder_work',
        2,
        'finder_work-detail',
        'detail',
        'tests/v2/fixtures/scrapers/finder_work/detail/response.json',
        'tests/v2/fixtures/scrapers/finder_work/detail/meta.json',
        'tests/v2/fixtures/scrapers/finder_work/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'hirehi',
        2,
        'hirehi-detail',
        'detail',
        'tests/v2/fixtures/scrapers/hirehi/detail/response.html',
        'tests/v2/fixtures/scrapers/hirehi/detail/meta.json',
        'tests/v2/fixtures/scrapers/hirehi/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'staff_am',
        2,
        'staff_am-detail',
        'detail',
        'tests/v2/fixtures/scrapers/staff_am/detail/response.html',
        'tests/v2/fixtures/scrapers/staff_am/detail/meta.json',
        'tests/v2/fixtures/scrapers/staff_am/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:ibs',
        0,
        'career:ibs-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/career_ibs/success/response.html',
        'tests/v2/fixtures/scrapers/career_ibs/success/meta.json',
        'tests/v2/fixtures/scrapers/career_ibs/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:ibs',
        1,
        'career:ibs-pagination',
        'pagination',
        'tests/v2/fixtures/scrapers/career_ibs/pagination/response.html',
        'tests/v2/fixtures/scrapers/career_ibs/pagination/meta.json',
        'tests/v2/fixtures/scrapers/career_ibs/pagination/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:ibs',
        2,
        'career:ibs-pagination-page-3',
        'pagination',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_3/response.html',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_3/meta.json',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_3/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:ibs',
        3,
        'career:ibs-pagination-page-4',
        'pagination',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_4/response.html',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_4/meta.json',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_4/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:ibs',
        4,
        'career:ibs-pagination-page-5',
        'pagination',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_5/response.html',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_5/meta.json',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_5/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:ibs',
        5,
        'career:ibs-pagination-page-6',
        'pagination',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_6/response.html',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_6/meta.json',
        'tests/v2/fixtures/scrapers/career_ibs/pagination_page_6/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:ibs',
        6,
        'career:ibs-detail',
        'detail',
        'tests/v2/fixtures/scrapers/career_ibs/detail/response.html',
        'tests/v2/fixtures/scrapers/career_ibs/detail/meta.json',
        'tests/v2/fixtures/scrapers/career_ibs/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:amocrm',
        0,
        'career:amocrm-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/career_amocrm/success/response.html',
        'tests/v2/fixtures/scrapers/career_amocrm/success/meta.json',
        'tests/v2/fixtures/scrapers/career_amocrm/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:amocrm',
        1,
        'career:amocrm-detail',
        'detail',
        'tests/v2/fixtures/scrapers/career_amocrm/detail/response.html',
        'tests/v2/fixtures/scrapers/career_amocrm/detail/meta.json',
        'tests/v2/fixtures/scrapers/career_amocrm/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:amocrm',
        2,
        'career:amocrm-detail-sections',
        'detail',
        'tests/v2/fixtures/scrapers/career_amocrm/detail_sections/response.html',
        'tests/v2/fixtures/scrapers/career_amocrm/detail_sections/meta.json',
        'tests/v2/fixtures/scrapers/career_amocrm/detail_sections/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:coinspaid',
        0,
        'career:coinspaid-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/career_coinspaid/success/response.json',
        'tests/v2/fixtures/scrapers/career_coinspaid/success/meta.json',
        'tests/v2/fixtures/scrapers/career_coinspaid/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:appfollow',
        0,
        'career:appfollow-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/career_appfollow/success/response.json',
        'tests/v2/fixtures/scrapers/career_appfollow/success/meta.json',
        'tests/v2/fixtures/scrapers/career_appfollow/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:appfollow',
        1,
        'career:appfollow-detail',
        'detail',
        'tests/v2/fixtures/scrapers/career_appfollow/detail/response.html',
        'tests/v2/fixtures/scrapers/career_appfollow/detail/meta.json',
        'tests/v2/fixtures/scrapers/career_appfollow/detail/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:appfollow',
        2,
        'career:appfollow-detail-backend',
        'detail',
        'tests/v2/fixtures/scrapers/career_appfollow/detail_backend/response.html',
        'tests/v2/fixtures/scrapers/career_appfollow/detail_backend/meta.json',
        'tests/v2/fixtures/scrapers/career_appfollow/detail_backend/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    ),
    (
        'career:airslate',
        0,
        'career:airslate-success',
        'success_non_empty',
        'tests/v2/fixtures/scrapers/career_airslate/success/response.json',
        'tests/v2/fixtures/scrapers/career_airslate/success/meta.json',
        'tests/v2/fixtures/scrapers/career_airslate/success/expected.raw.json',
        1,
        'codex_direct_fixture_review'
    );
