"""Canonical v2 run artifact names."""

RUN_DATABASE_FILENAME = "run.sqlite"
REPORT_HTML_FILENAME = "report.html"
EXECUTION_JSON_FILENAME = "execution.json"
SEARCH_RESULTS_JSON_FILENAME = "search-results.json"
ENRICHMENT_RESULTS_JSON_FILENAME = "enrichment-results.json"
DISCOVERED_SEARCH_RESULTS_JSON_FILENAME = "discovered-search-results.json"

__all__ = [
    "RUN_DATABASE_FILENAME",
    "REPORT_HTML_FILENAME",
    "EXECUTION_JSON_FILENAME",
    "SEARCH_RESULTS_JSON_FILENAME",
    "ENRICHMENT_RESULTS_JSON_FILENAME",
    "DISCOVERED_SEARCH_RESULTS_JSON_FILENAME",
]
