"""Output formatters for search results."""

from __future__ import annotations

import csv
import io
import json
from abc import ABC, abstractmethod

from job_harness.models import SearchResults


class BaseFormatter(ABC):
    @abstractmethod
    def format(self, results: SearchResults) -> str: ...


class MarkdownFormatter(BaseFormatter):
    def format(self, results: SearchResults) -> str:
        lines = []
        p = results.params
        lines.append(f"# Job Search: {p.query}")
        lines.append("")
        meta_parts = [f"Query: **{p.query}**"]
        if p.remote_only:
            meta_parts.append("Remote: yes")
        if p.experience:
            meta_parts.append(f"Experience: {p.experience}")
        if p.location:
            meta_parts.append(f"Location: {p.location}")
        meta_parts.append(f"Sources: all")
        lines.append(" | ".join(meta_parts))
        lines.append(f"Date: {results.timestamp}")
        lines.append(f"Results: {len(results.listings)}")
        lines.append("")
        lines.append("---")
        lines.append("")

        for i, l in enumerate(results.listings, 1):
            lines.append(f"### {i}. {l.title}")
            lines.append("")
            lines.append(f"- **URL:** {l.url}")
            lines.append(f"- **Company:** {l.company}")
            if l.salary:
                lines.append(f"- **Salary:** {l.salary}")
            lines.append(f"- **Experience:** {l.experience or 'not specified'}")
            fmt = "remote" if l.remote else "not specified"
            lines.append(f"- **Format:** {fmt}")
            if l.location:
                lines.append(f"- **Location:** {l.location}")
            if l.skills:
                lines.append(f"- **Skills:** {', '.join(l.skills[:10])}")
            if l.posted_date:
                lines.append(f"- **Posted:** {l.posted_date}")
            lines.append("")

        # Summary table
        lines.append("---")
        lines.append("")
        lines.append("## Summary")
        lines.append("")
        lines.append("| # | Company | Salary | Format | Experience |")
        lines.append("|---|---------|--------|--------|------------|")
        for i, l in enumerate(results.listings, 1):
            fmt = "remote" if l.remote else "not specified"
            lines.append(f"| {i} | {l.company} | {l.salary or 'not specified'} | {fmt} | {l.experience or 'not specified'} |")

        lines.append("")
        lines.append(f"> Generated by job-harness — {results.timestamp}")
        return "\n".join(lines)


class JsonFormatter(BaseFormatter):
    def format(self, results: SearchResults) -> str:
        return json.dumps(results.to_dict(), ensure_ascii=False, indent=2)


class CsvFormatter(BaseFormatter):
    def format(self, results: SearchResults) -> str:
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["title", "url", "company", "salary", "experience", "remote", "location", "skills", "source", "posted_date"])
        for l in results.listings:
            writer.writerow([
                l.title,
                l.url,
                l.company,
                l.salary or "",
                l.experience or "",
                l.remote,
                l.location or "",
                "; ".join(l.skills),
                l.source,
                l.posted_date or "",
            ])
        return output.getvalue()


FORMATTERS: dict[str, type[BaseFormatter]] = {
    "markdown": MarkdownFormatter,
    "json": JsonFormatter,
    "csv": CsvFormatter,
}


def get_formatter(format_name: str) -> BaseFormatter:
    cls = FORMATTERS.get(format_name)
    if not cls:
        raise ValueError(f"Unknown format: {format_name}. Available: {list(FORMATTERS.keys())}")
    return cls()
