"""Output formatters for search results."""

from __future__ import annotations

import csv
import io
import json
from abc import ABC, abstractmethod

from job_harness.models import SearchResults


class BaseFormatter(ABC):
    @abstractmethod
    def format(self, results: SearchResults) -> str: ...


class MarkdownFormatter(BaseFormatter):
    def format(self, results: SearchResults) -> str:
        lines = []
        p = results.params
        lines.append(f"# Job Search: {p.query}")
        lines.append("")
        meta_parts = [f"Query: **{p.query}**"]
        if p.country:
            meta_parts.append(f"Country: {p.country}")
        if p.remote_only:
            meta_parts.append("Remote: yes")
        if p.experience:
            meta_parts.append(f"Experience: {p.experience}")
        if p.location:
            meta_parts.append(f"Location: {p.location}")
        meta_parts.append("Sources: all")
        lines.append(" | ".join(meta_parts))
        lines.append(f"Date: {results.timestamp}")
        lines.append(f"Results: {len(results.listings)}")
        lines.append("")
        lines.append("---")
        lines.append("")

        source_statuses = results.summary.get("source_statuses", []) if results.summary else []
        if source_statuses:
            lines.append("## Source Status")
            lines.append("")
            lines.append("| Source | Status | Raw | After filters | After dedupe | Duration |")
            lines.append("|---|---|---:|---:|---:|---:|")
            for status in source_statuses:
                lines.append(
                    f"| {status['source']} | {status['status']} | {status['raw_count']} | "
                    f"{status['after_filter_count']} | {status['after_dedupe_count']} | "
                    f"{status['duration_ms']} ms |"
                )
            lines.append("")
            lines.append("---")
            lines.append("")

        for i, listing in enumerate(results.listings, 1):
            lines.append(f"### {i}. {listing.title}")
            lines.append("")
            lines.append(f"- **URL:** {listing.url}")
            lines.append(f"- **Company:** {listing.company}")
            if listing.country:
                lines.append(f"- **Country:** {listing.country}")
            if listing.salary:
                lines.append(f"- **Salary:** {listing.salary}")
            lines.append(f"- **Experience:** {listing.experience or 'not specified'}")
            fmt = "remote" if listing.remote else "not specified"
            lines.append(f"- **Format:** {fmt}")
            if listing.location:
                lines.append(f"- **Location:** {listing.location}")
            if listing.skills:
                lines.append(f"- **Skills:** {', '.join(listing.skills[:10])}")
            if listing.posted_date:
                lines.append(f"- **Posted:** {listing.posted_date}")
            lines.append("")

        # Summary table
        lines.append("---")
        lines.append("")
        lines.append("## Summary")
        lines.append("")
        lines.append("| # | Company | Country | Salary | Format | Experience |")
        lines.append("|---|---------|---------|--------|--------|------------|")
        for i, listing in enumerate(results.listings, 1):
            fmt = "remote" if listing.remote else "not specified"
            lines.append(
                f"| {i} | {listing.company} | {listing.country or 'not specified'} | "
                f"{listing.salary or 'not specified'} | {fmt} | {listing.experience or 'not specified'} |"
            )

        lines.append("")
        lines.append(f"> Generated by job-harness — {results.timestamp}")
        return "\n".join(lines)


class JsonFormatter(BaseFormatter):
    def format(self, results: SearchResults) -> str:
        return json.dumps(results.to_dict(), ensure_ascii=False, indent=2)


class CsvFormatter(BaseFormatter):
    def format(self, results: SearchResults) -> str:
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["title", "url", "company", "country", "salary", "experience", "remote", "location", "skills", "source", "posted_date"])
        for listing in results.listings:
            writer.writerow([
                listing.title,
                listing.url,
                listing.company,
                listing.country or "",
                listing.salary or "",
                listing.experience or "",
                listing.remote,
                listing.location or "",
                "; ".join(listing.skills),
                listing.source,
                listing.posted_date or "",
            ])
        return output.getvalue()


FORMATTERS: dict[str, type[BaseFormatter]] = {
    "markdown": MarkdownFormatter,
    "json": JsonFormatter,
    "csv": CsvFormatter,
}


def get_formatter(format_name: str) -> BaseFormatter:
    cls = FORMATTERS.get(format_name)
    if not cls:
        raise ValueError(f"Unknown format: {format_name}. Available: {list(FORMATTERS.keys())}")
    return cls()
